color0 #{{ term0.hex }}
color1 #{{ term1.hex }}
color2 #{{ term2.hex }}
color3 #{{ term3.hex }}
color4 #{{ term4.hex }}
color5 #{{ term5.hex }}
color6 #{{ term6.hex }}
color7 #{{ term7.hex }}
color8 #{{ term8.hex }}
color9 #{{ term9.hex }}
color10 #{{ term10.hex }}
color11 #{{ term11.hex }}
color12 #{{ term12.hex }}
color13 #{{ term13.hex }}
color14 #{{ term14.hex }}
color15 #{{ term15.hex }}

cursor                #{{ onSurface.hex }}
cursor_text_color     #{{ surface.hex }}
background            #{{ surface.hex }}
foreground            #{{ onSurface.hex }}
selection_foreground  #{{ onSurfaceVariant.hex }}
selection_background  #{{ surfaceVariant.hex }}
active_border_color   #{{ primary.hex }}
inactive_border_color #{{ surfaceVariant.hex }}
url_color             #{{ primary.hex }}

active_tab_foreground   #{{ onPrimary.hex }}
active_tab_background   #{{ primary.hex }}
inactive_tab_foreground #{{ onSurfaceVariant.hex }}
inactive_tab_background #{{ surfaceVariant.hex }}
cursor_trail_color      #{{ onSurfaceVariant.hex }}
